Remove `chain_indices` table
SiaFoundation/walletd pull request #107
Opened 2024-04-23 09:22 UTC by peterjan

This PR removes the `chain_indices` table. I'm not entirely sure that's what we want but since we were discussing getting rid of the `CASCADE` deletes I don't see a good reason to keep the table. Creating it and linking it is more of a nuisance than anything else imo, if you don't get the upside of the cascaded deletes.

I hit an interesting test failure in the process, an underflow is triggered in `TestEphemeralBalance` which is interesting because on `master` there are no orphaned indices, but now there are orphaned `siacoin_elements`... so I'm a little bit puzzled still on why that is. 

I think there might also be a bug in `RevertOrphans` because we loop over the orphaned indices and it seems we only deal with the balances of the last orphan. (consensus.go:751) Since I'm not sure whether we want to get rid of the `chain_indices` entirely I'm going to keep it in `DRAFT` until tomorrow when Nate is back from being OOO.

2024-04-23 17:07 UTC, n8maninger commented
The failure in `TestEphemeralBalance` is valid because we're associating the unspent siacoin element in a reverted block with the block ID we're reverting. We need to remove the chain index association from elements completely, but then we run into problems removing orphans.

2024-04-23 21:11 UTC, n8maninger requested changes

2024-04-24 11:09 UTC, peterjan commented
@n8maninger this PR now removes the `chain_indices` table and I believe that the behaviour before and after merging is the same. I think I found a bug though in how we handle reverts and orphans, will open another PR to address that issue, still have one broken test.

2024-04-24 20:42 UTC, n8maninger approved these changes

2024-04-24 20:42 UTC, merged